config/routes.rb
Rails.application.routes.draw do
  mount Pixelpress::Engine => "rails" if Rails.env.development?

  resources :games do
    collection do
      get "pdfkit", "weasyprint", "rails_pdf"
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/pdf_report.rb
# frozen_string_literal: true	

# Prepare and render order samples report to pdf	
class PdfReport	
  def initialize(game)	
    @game = game
  end	

  def to_pdf	
    ApplicationController.render template: "/pdf/report"		
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'benchmark/ips'
require 'benchmark/ipsa'

class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @games = Game.all
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def pdfkit
    @game = Game.first

    respond_to do |format|
      format.pdf do
        report = PdfReport.new(@game)
        
        send_data report.to_pdf, filename: "nalaz", disposition: 'inline',
          type: 'application/pdf'
      end
    end
  end

  def weasyprint
    @game = Game.first
    
    # respond_to do |format|
    #   format.pdf do
    #     report = OrderPrinter.report(@game)
        
    #     send_data report.pdf.read, filename: "report", disposition: 'inline',
    #       type: 'application/pdf'
    #   end
    # end

    Benchmark.ipsa do |x| 
      x.report("weasyprint") do 
        weasyprint = OrderPrinter.report(@game)
        weasyprint.pdf.read
      end
      x.report("pdfkit") do 
        pdfkit = PdfReport.new(@game)
        pdfkit.to_pdf
      end
      x.report("rails_pdf") do 
        rails_pdf = RailsPDF.template("index/index.pug.erb").locals(game: @game)
        rails_pdf.render { |data| data }
      end

      # x.compare!
    end

  end

  def rails_pdf
    RailsPDF.template("index/index.pug.erb").locals(game: Game.first).render do |data|
      send_data(data, type: 'application/pdf', disposition: 'inline', filename: 'report.pdf')
    end
  end

  def download_project
    RailsPDF.template("report3/invoice.pug.erb").locals(project: Project.first).render do |data|
      send_data(data, type: 'application/pdf', disposition: 'inline', filename: 'report.pdf')
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:title, :genre, :platform)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>

  <div class="field">
    <%= form.label :platform %>
    <%= form.text_field :platform %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Pdfkit</th>
      <th>Weasyprint</th>
      <th>Rails_pdf</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= link_to 'Pdfkit', pdfkit_games_path(format: :pdf) %></td>
        <td><%= link_to 'Weasyprint', weasyprint_games_path(format: :pdf) %></td>
        <td><%= link_to 'Rails_pdf', rails_pdf_games_path(format: :pdf) %></td>

      </tr>
  </tbody>
</table>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Genre</th>
      <th>Platform</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.title %></td>
        <td><%= game.genre %></td>
        <td><%= game.platform %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestPdfReports</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/printer.pdf.erb
<div>
  <%= yield %>
</div>

app/views/layouts/report_pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="initial-scale=1" />
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pdf/report.pdf.erb
<link rel="stylesheet" type="text/css" href="<%= Rails.root %>/app/pdf/shared/stylesheets/font-awesome/style.css">
<link rel="stylesheet" type="text/css" href="<%= Rails.root %>/app/pdf/shared/stylesheets/bootstrap/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="<%= Rails.root %>/app/pdf/shared/stylesheets/bootstrap/bootstrap.print.css">
<link rel="stylesheet" type="text/css" href="<%= Rails.root %>/app/pdf/index/stylesheets/template.css">

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1> Sales Report 2019 for </h1>
      <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam velit urna, tincidunt vel mauris sit amet, dictum fermentum diam. Integer dignissim lorem ante, eget ultrices libero tincidunt at. Integer ut elit volutpat mauris suscipit tempus eget a ipsum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam mattis nisl vel tellus bibendum, eu vulputate ligula semper. Nulla varius nulla sit amet nisl rhoncus dapibus. </p>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th> SKU </th>
            <th> Title </th>
            <th> East </th>
            <th> West </th>
            <th> North </th>
            <th> South </th>
            <th> Estimated $ </th>
          </th>
        </thead>
        
        <tbody>
          <% 200.times do %>
            <tr>
              <td> <%= link_to rand(1_000_000).to_s.rjust(8, "0"), '#' %> </td>
              <td> <%= ['Phone', 'Computer', 'Laptop', 'PC', 'Beer'].sample %> </td>
              <td class="text-success"> <%= rand(100) %> </td>
              <td class="text-success"> <%= rand(100) %> </td>
              <td class="text-danger"> <%= rand(100) %> </td>
              <td class="text-danger"> <%= rand(100) %> </td>
              <td> <%= number_to_currency rand(10000), precision: 0 %> </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<style>

template#page-footer
  style(type='text/css').
    .pdfheader {
      font-size: 9px;
      color: #555;
      font-family: Helvetica;
      font-weight: normal;
      width: 1000px;
      border-top: 1px solid #ccc;
      margin-left: 10%;
      margin-right: 10%;
      padding-top: 1mm;
      margin-bottom: -1mm;
      text-align: center;
    }
    .pageNumber {
      color: red;
    }
  
  .pdfheader Page #[span.pageNumber] / #[span.totalPages]

  </style>

app/views/printers/order/report.pdf.erb
<link rel="stylesheet" type="text/css" href="<%= Rails.root %>/app/pdf/shared/stylesheets/font-awesome/style.css">
<link rel="stylesheet" type="text/css" href="<%= Rails.root %>/app/pdf/shared/stylesheets/bootstrap/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="<%= Rails.root %>/app/pdf/shared/stylesheets/bootstrap/bootstrap.print.css">
<link rel="stylesheet" type="text/css" href="<%= Rails.root %>/app/pdf/index/stylesheets/template.css">

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1> Sales Report 2019 for </h1>
      <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam velit urna, tincidunt vel mauris sit amet, dictum fermentum diam. Integer dignissim lorem ante, eget ultrices libero tincidunt at. Integer ut elit volutpat mauris suscipit tempus eget a ipsum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam mattis nisl vel tellus bibendum, eu vulputate ligula semper. Nulla varius nulla sit amet nisl rhoncus dapibus. </p>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th> SKU </th>
            <th> Title </th>
            <th> East </th>
            <th> West </th>
            <th> North </th>
            <th> South </th>
            <th> Estimated $ </th>
          </th>
        </thead>
        
        <tbody>
          <% 200.times do %>
            <tr>
              <td> <%= link_to rand(1_000_000).to_s.rjust(8, "0"), '#' %> </td>
              <td> <%= ['Phone', 'Computer', 'Laptop', 'PC', 'Beer'].sample %> </td>
              <td class="text-success"> <%= rand(100) %> </td>
              <td class="text-success"> <%= rand(100) %> </td>
              <td class="text-danger"> <%= rand(100) %> </td>
              <td class="text-danger"> <%= rand(100) %> </td>
              <td> <%= number_to_currency rand(10000), precision: 0 %> </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<style>
@page {
      size: A4;
      margin: 0.34in 0.34in 0.50in 0.34in;
}
template#page-footer
  style(type='text/css').
    .pdfheader {
      font-size: 9px;
      color: #555;
      font-family: Helvetica;
      font-weight: normal;
      width: 1000px;
      border-top: 1px solid #ccc;
      margin-left: 10%;
      margin-right: 10%;
      padding-top: 1mm;
      margin-bottom: -1mm;
      text-align: center;
    }
    .pageNumber {
      color: red;
    }
  
  .pdfheader Page #[span.pageNumber] / #[span.totalPages]

  </style>